# Blog info
blog_name: Yenole
slogan: 夜の乐
url: http://2ustc.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: cocos,golang,python

home_nav:
  - name: 博客
    url: /archives
    target_blank: false #不在新页面打开
  - name: 项目
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/yenole
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  # - name: RSS
  #   url: /atom.xml
  #   target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 导航

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 Netxy@vip.qq.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持
  tip: 扫一扫，支持一下
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.jpg
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.jpg




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: 

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: dark # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 

# Comment service
disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Apr，1992，Spring."
    - "喜欢设计，擅长编程，喜欢睡懒觉."
    - "软件工程师，网站 / 游戏 / 服务端."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@Yenole"
    text_value_url: https://github.com/yenole
  # - type: weibo
  #   icon: icon-weibo
  #   text_key: 微博
  #   text_value: "@forsigner"
  #   text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "Netxy@vip.qq.com"
  - type: location
    icon: icon-location
    text_value: 安徽

link:
  - name: Google
    info: 身体和灵魂，总有一个在路上
    url: https://google.com/
    avatar: https://avatars2.githubusercontent.com/u/1342004?v=4&s=200


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
